version: '3'
services:
  web:
    container_name: jianshu
    build:
      context: .
      dockerfile: dockerfile-dev
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "jianshu"
      MYSQL_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
